### ISSUE TITLE
screen demo problems on pico

### ISSUE THREAD

**Issue by AndrewWang1111** [blippy/rpi#1]
I clone this demo  and  tested on my raspberry pico .Found  that  the 1306 screen  sometimes  up side down  or  mirrored,sometimes  won't light after  repower on.  Don't kown it is a bug or wrong with my hardware ~

**Comment by blippy** [comment]
Are you using a 128x64 OLED, or a 128x32 OLED?

There more chance of there being a bug in my code than with a fault in the OLED. Have you tried porgramming the OLED with another MCU or Pi?

**Comment by AndrewWang1111** [comment]
Its'  a 128*64 LCD, work well with pi 3B.Even though, this is the only example for pico to drive 1306,in such few days . Thanks for your effort~~

**Comment by blippy** [comment]
No problemo. Hmmm. Well, that has me baffled. I'll try my code out again, just to confirm that my code still works and something hasn't slipped through.

**Comment by panchalnikunj** [comment]
https://www.youtube.com/watch?v=ziuvFON81ZE

Try this, everything is explained.

**Comment by blippy** [comment]
> I'll try my code out again, just to confirm that my code still works and something hasn't slipped through.

I tried the code, and it seems to work. At least one other guy has it working, too. I'm not really sure how I can proceed on this.

**Comment by blippy** [comment]
Can I close this issue? Is anyone else having the same problem?

**Comment by beshrkayali** [comment]
Tried your code with a 128x32 and it worked great!
