### ISSUE TITLE
1306 RPI-SDK Wanted Additions Set Cursor

### ISSUE THREAD

**Issue by amohsen01** [blippy/rpi#4]
It would be nice to add a set cursor to be able to set the cursor in main without resulting to add spaces newlines 

`
void setCursorX(int x){
	int pos=8;
	cursorx=pos*x;

}
void setCursorY(int x){
	int pos=8;
	cursory=pos*x;
`

**Comment by blippy** [comment]
Implemented in commit https://github.com/blippy/rpi/commit/81506076a5ccb2874645a517b912d125392a1090
